(()=>{
const studio={category:'Todos',context:{}};
const formats={a4:'A4 vertical',landscape:'A4 horizontal',thermal80:'Térmico 80 mm',thermal58:'Térmico 58 mm',label:'Etiqueta'};
const styles={official:'Oficial tabular'};
const fieldSets={
 sales:[['number','Número'],['date','Fecha'],['time','Hora'],['client','Cliente'],['seller','Vendedor'],['payment','Pago'],['kind','Tipo'],['items','Ítems'],['subtotal','Subtotal'],['discount','Descuento'],['total','Total']],
 saleItems:[['code','Código'],['product','Producto'],['quantity','Cantidad'],['unit','Unidad'],['unitPrice','Precio unitario'],['discount','Descuento'],['total','Total']],
 products:[['code','Código'],['name','Producto'],['category','Categoría'],['unit','Unidad'],['stock','Stock'],['minimum','Mínimo'],['cost','Costo'],['price','Precio'],['wholesale','Mayorista'],['supplier','Proveedor'],['profit','Margen']],
 clients:[['code','Código'],['name','Cliente'],['type','Tipo'],['document','CI / NIT'],['phone','Teléfono'],['city','Ciudad'],['balance','Saldo'],['purchases','Compras'],['total','Total comprado']],
 cash:[['date','Fecha'],['time','Hora'],['client','Cliente'],['type','Tipo'],['description','Descripción'],['employee','Funcionario'],['income','Entrada'],['expense','Salida'],['amount','Valor']],
 stock:[['date','Fecha'],['time','Hora'],['product','Producto'],['code','Código'],['type','Movimiento'],['quantity','Cantidad'],['reason','Motivo'],['employee','Funcionario']],
 employees:[['name','Funcionario'],['role','Cargo'],['sales','Ventas'],['total','Facturado'],['ticket','Ticket promedio'],['commission','Comisión'],['goal','Meta']],
 employeeSales:[['number','Número'],['date','Fecha'],['time','Hora'],['client','Cliente'],['payment','Pago'],['items','Ítems'],['total','Total']],
 sellerSummary:[['rank','Posición'],['name','Vendedor'],['role','Cargo'],['sales','Ventas'],['items','Artículos'],['total','Facturado'],['ticket','Ticket promedio'],['share','Participación'],['highlight','Resultado']],
 closings:[['date','Fecha'],['opened','Apertura'],['closed','Cierre'],['employee','Funcionario'],['income','Entradas'],['expense','Salidas'],['total','Saldo'],['reason','Motivo']],
 cashClosing:[['date','Fecha'],['time','Hora'],['type','Tipo'],['description','Descripción'],['employee','Funcionario'],['payment','Medio de pago'],['income','Entrada'],['expense','Salida'],['balance','Saldo acumulado']],
 clientLedger:[['date','Fecha'],['time','Hora'],['type','Operación'],['description','Descripción'],['reference','Referencia'],['payment','Pago'],['amount','Valor'],['debit','Débito'],['credit','Crédito'],['balance','Saldo']],
 payables:[['due','Vencimiento'],['description','Descripción'],['supplier','Proveedor'],['status','Estado'],['amount','Valor']],
 purchases:[['date','Fecha'],['document','Documento'],['supplier','Proveedor'],['product','Producto'],['quantity','Cantidad'],['cost','Costo'],['total','Total']],
 fiscal:[['date','Fecha'],['number','Número'],['model','Modelo'],['client','Cliente'],['cfop','CFOP'],['status','Estado'],['total','Total']]
};
const modelData=[
 ['sale-report','Informe detallado de venta','Documentos','saleItems',['a4','landscape'],['code','product','quantity','unitPrice','discount','total'],'receipt','sale'],
 ['sale-receipt','Informe de venta A4','Documentos','saleItems',['a4'],['code','product','quantity','unitPrice','total'],'receipt','sale'],
 ['zona-franca-invoice','Factura de venta de Zona Franca','Fiscal','saleItems',['a4'],['code','quantity','product','unit','unitPrice','discount','total'],'receipt','sale'],
 ['budget','Presupuesto / cotización','Documentos','sales',['a4','thermal80'],['number','date','client','seller','items','subtotal','discount','total'],'receipt'],
 ['order','Pedido de venta','Documentos','sales',['a4','thermal80'],['number','date','client','seller','payment','items','total'],'receipt'],
 ['payment-receipt','Recibo de pago','Documentos','cash',['a4','thermal80','thermal58'],['date','client','description','employee','amount'],'cash'],
 ['cash-closing','Cierre detallado de caja','Documentos','cashClosing',['a4','landscape','thermal80'],['date','time','type','description','employee','payment','income','expense','balance'],'wallet'],
 ['product-label','Etiqueta de producto y precio','Documentos','products',['label','thermal58','thermal80'],['code','name','price'],'tag'],
 ['price-list','Lista de precios','Documentos','products',['a4','landscape'],['code','name','unit','price','wholesale'],'tag'],
 ['stock-count','Hoja de inventario físico','Documentos','products',['a4','landscape'],['code','name','category','unit','stock'],'box'],
 ['client-statement','Extracto y estado de cuenta del cliente','Documentos','clientLedger',['a4','landscape','thermal80'],['date','type','description','reference','payment','amount','debit','credit','balance'],'users','client'],
 ['client-file','Ficha del cliente','Documentos','clients',['a4'],['code','name','type','document','phone','city','balance'],'users'],
 ['employee-performance','Resumen de desempeño del funcionario','Documentos','employeeSales',['a4','landscape'],['number','date','client','payment','items','total'],'badge','employee'],
 ['product-file','Ficha del producto','Documentos','products',['a4'],['code','name','category','unit','stock','cost','price','wholesale','supplier'],'box'],
 ['general-sales-report','Informe general de ventas y vendedores','Ventas','sellerSummary',['landscape','a4'],['rank','name','role','sales','items','total','ticket','share','highlight'],'chart'],
 ['revenue','Facturación','Ventas','sales',['a4','landscape'],['date','number','client','seller','total'],'chart'],
 ['sales-count','Cantidad de ventas','Ventas','sales',['a4','landscape'],['date','number','kind','items','total'],'chart'],
 ['average-ticket','Ticket promedio','Ventas','sales',['a4'],['date','seller','client','total'],'chart'],
 ['gross-profit','Lucro bruto','Rentabilidad','sales',['a4','landscape'],['date','number','seller','subtotal','discount','total'],'chart'],
 ['payment-methods','Ventas por medio de pago','Ventas','sales',['a4','landscape'],['date','number','client','payment','total'],'cash'],
 ['seller-commission','Comisión por vendedor','Ventas','sellerSummary',['a4','landscape'],['rank','name','role','sales','total','ticket','share'],'badge'],
 ['sales-products','Ventas por producto','Ventas','products',['a4','landscape'],['code','name','category','stock','price','profit'],'box'],
 ['sales-category','Ventas por categoría y producto','Ventas','products',['a4','landscape'],['category','code','name','stock','price'],'box'],
 ['sales-client-category','Ventas por cliente y categoría','Ventas','clients',['a4','landscape'],['code','name','type','purchases','total','balance'],'users'],
 ['client-ranking','Ranking de clientes','Clientes','clients',['a4','landscape'],['name','type','purchases','total','balance'],'users'],
 ['client-products','Productos comprados por cliente','Clientes','clients',['a4','landscape'],['code','name','purchases','total','balance'],'users'],
 ['product-clients','Clientes compradores por producto','Clientes','products',['a4','landscape'],['code','name','category','stock','price'],'users'],
 ['peak-hours','Horario de pico','Ventas','sales',['a4'],['date','time','number','client','total'],'calendar'],
 ['product-profit','Rentabilidad por producto','Rentabilidad','products',['a4','landscape'],['code','name','cost','price','profit','stock'],'chart'],
 ['income-expense','Ingresos y gastos','Rentabilidad','cash',['a4','landscape'],['date','type','description','employee','income','expense','amount'],'wallet'],
 ['stock-movements','Movimiento de productos','Inventario','stock',['a4','landscape'],['date','product','code','type','quantity','reason','employee'],'transfer'],
 ['internal-use','Uso y consumo interno','Inventario','stock',['a4','landscape'],['date','product','code','quantity','reason','employee'],'box'],
 ['stock-position','Posición actual de stock','Inventario','products',['a4','landscape'],['code','name','category','stock','minimum','cost','price'],'box'],
 ['payables-due','Cuentas por vencer','Financiero','payables',['a4','landscape'],['due','description','supplier','status','amount'],'calendar'],
 ['payables-paid','Cuentas pagadas','Financiero','payables',['a4','landscape'],['due','description','supplier','status','amount'],'check'],
 ['purchases-product','Compras por producto','Compras','purchases',['a4','landscape'],['date','document','product','quantity','cost','total'],'box'],
 ['purchases-supplier','Compras por proveedor','Compras','purchases',['a4','landscape'],['date','document','supplier','quantity','total'],'store'],
 ['supplier-sales','Ventas por proveedor','Compras','products',['a4','landscape'],['supplier','code','name','stock','cost','price','profit'],'store'],
 ['fiscal-issued','Documentos fiscales emitidos','Fiscal','fiscal',['a4','landscape'],['date','number','model','client','status','total'],'receipt'],
 ['nfce-list','Relación de NFC-e','Fiscal','fiscal',['a4','landscape'],['date','number','client','status','total'],'receipt'],
 ['nfe-list','Relación de NF-e','Fiscal','fiscal',['a4','landscape'],['date','number','client','status','total'],'receipt'],
 ['cfop','Documentos por CFOP','Fiscal','fiscal',['a4','landscape'],['date','number','model','cfop','status','total'],'receipt'],
 ['sales-tax','Ventas por tributación','Fiscal','fiscal',['a4','landscape'],['date','number','model','cfop','client','total'],'chart']
];
const models=modelData.map(([id,title,category,source,allowedFormats,defaultFields,icon,contextType=''])=>({id,title,category,source,allowedFormats,defaultFields,icon,contextType}));
const modelById=id=>models.find(model=>model.id===id);
const ensureSettings=()=>state.settings.documentTemplates||(state.settings.documentTemplates={});
const ensureGenerated=()=>state.generatedDocuments||(state.generatedDocuments=[]);
const isoDay=value=>{const d=value?new Date(value):new Date();return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)};
const currentMonthRange=()=>{const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1);return{dateFrom:isoDay(start),dateTo:isoDay(now)}};
const datedSources=new Set(['sales','employeeSales','sellerSummary','cash','stock','clientLedger','cashClosing','closings','saleItems']);
const defaultFooterFor=model=>model.id==='sale-receipt'?'Comprobante comercial de venta. No sustituye una factura fiscal homologada por el SIN.':model.id==='zona-franca-invoice'?'Modelo comercial. La validez fiscal requiere integración homologada con el SIN.':'Documento generado por GRASSI PDV & ERP';
const configFor=model=>({title:model.title,format:model.allowedFormats[0],fontSize:'medium',...currentMonthRange(),showLogo:true,showBusiness:true,showPeriod:true,showSignature:false,footer:defaultFooterFor(model),fields:model.defaultFields,...ensureSettings()[model.id],...Object.fromEntries(Object.entries(studio.context||{}).filter(([key])=>['dateFrom','dateTo'].includes(key))),style:'official',accent:'#111111'});
const fieldLabel=(source,key)=>fieldSets[source]?.find(([id])=>id===key)?.[1]||key;
const safeDate=value=>{try{return date(value)}catch{return'—'}};
const safeTime=value=>{try{return time(value)}catch{return'—'}};
const parseBoundary=(value,end=false)=>{if(!value)return end?Infinity:-Infinity;return new Date(`${value}T${end?'23:59:59.999':'00:00:00'}`).getTime()};
const inRange=(value,config={})=>{const current=new Date(value).getTime();return Number.isFinite(current)&&current>=parseBoundary(config.dateFrom)&&current<=parseBoundary(config.dateTo,true)};
const stripInternal=row=>Object.fromEntries(Object.entries(row).filter(([key])=>!key.startsWith('_')));
const salesInRange=config=>(state.sales||[]).filter(s=>(s.type||'Venta')==='Venta'&&inRange(s.date,config));
const saleFor=(context=studio.context)=>(state.sales||[]).find(s=>s.id===context.saleId||s.uuid===context.saleId||s.clientSaleId===context.saleId);
const employeeFor=(context=studio.context)=>(state.employees||[]).find(e=>e.id===context.employeeId||e.name===context.employeeName);
const clientFor=(context=studio.context)=>(state.clients||[]).find(c=>c.id===context.clientId||c.name===context.clientName);
function sellerRows(config){const sales=salesInRange(config),total=sum(sales,'total'),groups=new Map();sales.forEach(s=>{const key=s.employeeId||s.employee||'Sin vendedor',current=groups.get(key)||{name:s.employee||'Sin vendedor',employeeId:s.employeeId,sales:0,items:0,total:0};current.sales++;current.items+=Number(s.items||0);current.total+=Number(s.total||0);groups.set(key,current)});return[...groups.values()].map(row=>{const employee=(state.employees||[]).find(e=>e.id===row.employeeId||e.name===row.name);return{...row,role:employee?.role||'Vendedor'}}).sort((a,b)=>b.total-a.total).map((row,index)=>({rank:`${index+1}º`,name:row.name,role:row.role,sales:row.sales,items:row.items,total:money(row.total),ticket:money(row.sales?row.total/row.sales:0),share:`${total?Math.round(row.total/total*100):0}%`,highlight:index===0?'Mayor facturación':'—'}))}
function cashClosingMovements(context,config){const closing=context.closingId?(state.closings||[]).find(c=>c.id===context.closingId):null;if(closing){const start=new Date(closing.openedAt||closing.date).getTime(),end=new Date(closing.date).getTime();return(state.cash||[]).filter(m=>{const when=new Date(m.date).getTime();return when>=start&&when<=end}).sort((a,b)=>new Date(a.date)-new Date(b.date))}return(state.cash||[]).filter(m=>inRange(m.date,config)).sort((a,b)=>new Date(a.date)-new Date(b.date))}
function cashClosingRows(context,config){let balance=0;return cashClosingMovements(context,config).map(m=>{balance+=m.type==='in'?Number(m.amount||0):-Number(m.amount||0);const parts=String(m.description||'').split('—');return{_date:m.date,date:safeDate(m.date),time:safeTime(m.date),type:m.type==='in'?'Entrada':'Salida',description:parts[0]?.trim()||'—',employee:m.employee||'—',payment:parts[1]?.trim()||'—',income:m.type==='in'?money(m.amount):'—',expense:m.type==='out'?money(m.amount):'—',balance:money(balance)}})}
function clientLedgerRows(context,config){const client=clientFor(context);if(!client)return[];const ledger=[...(client.ledger||[])],sales=(state.sales||[]).filter(s=>(s.clientId&&s.clientId===client.id)||s.client===client.name),linked=new Set();sales.forEach(s=>ledger.forEach((entry,index)=>{if(entry.saleId===s.uuid||String(entry.description||'').includes(s.id))linked.add(index)}));const ledgerImpact=ledger.reduce((n,entry)=>n+(entry.type==='credit'?Number(entry.amount||0):-Number(entry.amount||0)),0);let balance=Number(client.balance||0)-ledgerImpact;const events=[...sales.map(s=>({date:s.date,type:'Venta',description:`Venta ${s.id}`,reference:s.id,payment:s.payment||'—',amount:Number(s.total||0),impact:s.payment==='Cuenta cliente'?-Number(s.total||0):0})),...ledger.filter((_,index)=>!linked.has(index)).map(entry=>({date:entry.date,type:entry.type==='credit'?'Crédito / pago':'Débito',description:entry.description||'Movimiento de cuenta',reference:entry.reference||'Cuenta corriente',payment:entry.paymentMethod||'—',amount:Number(entry.amount||0),impact:entry.type==='credit'?Number(entry.amount||0):-Number(entry.amount||0)}))].sort((a,b)=>new Date(a.date)-new Date(b.date));return events.map(event=>{balance+=event.impact;return{_date:event.date,date:safeDate(event.date),time:safeTime(event.date),type:event.type,description:event.description,reference:event.reference,payment:event.payment,amount:money(event.amount),debit:event.impact<0?money(Math.abs(event.impact)):'—',credit:event.impact>0?money(event.impact):'—',balance:money(balance)}}).filter(row=>inRange(row._date,config))}
function sourceRows(source,context=studio.context,config=currentMonthRange()){
 const selectedSale=saleFor(context),selectedEmployee=employeeFor(context);
 if(source==='saleItems'){const items=selectedSale?.receiptItems||selectedSale?.itemsDetail||[];return items.map((item,index)=>{const quantity=Number(item.quantity||item.qty||0),unitPrice=Number(item.unitPrice??item.price??0),basePrice=Number(item.basePrice??unitPrice),lineDiscount=Math.max(0,(basePrice-unitPrice)*quantity),product=(state.products||[]).find(entry=>entry.id===(item.productId||item.product_id||item.id));return{code:item.code||item.productCode||product?.code||item.product_id||String(index).padStart(6,'0'),product:item.name||item.product||item.description||product?.name||'Producto',quantity:quantity.toLocaleString(locale()),unit:item.unit||product?.unit||'Unidad',unitPrice:money(unitPrice),discount:money(lineDiscount),total:money(item.total??quantity*unitPrice)}})}
 if(source==='sales')return(state.sales||[]).filter(s=>inRange(s.date,config)).map(s=>({number:s.id,date:safeDate(s.date),time:safeTime(s.date),client:s.client||'Consumidor final',seller:s.employee||'—',payment:s.payment||'—',kind:s.type||'Venta',items:s.items||0,subtotal:money(s.subtotal??s.total),discount:money(s.discountTotal||0),total:money(s.total)}));
 if(source==='employeeSales')return(state.sales||[]).filter(s=>inRange(s.date,config)&&((selectedEmployee?.id&&s.employeeId===selectedEmployee.id)||(selectedEmployee?.name&&s.employee===selectedEmployee.name))).map(s=>({number:s.id,date:safeDate(s.date),time:safeTime(s.date),client:s.client||'Consumidor final',payment:s.payment||'—',items:s.items||0,total:money(s.total)}));
 if(source==='products')return(state.products||[]).map(p=>({code:p.code||p.ean||'—',name:p.name,category:p.category||'—',unit:p.unit||'Unidad',stock:Number(p.stock||0).toLocaleString(locale()),minimum:Number(p.minStock||0).toLocaleString(locale()),cost:money(p.cost),price:money(p.price),wholesale:money(p.wholesale),supplier:p.supplier||'—',profit:`${p.cost?Math.round((p.price-p.cost)/p.cost*100):0}%`}));
 if(source==='clients')return(state.clients||[]).map(c=>({code:c.code||'—',name:c.name,type:c.type||'—',document:c.document||'—',phone:c.phone||'—',city:c.city||'—',balance:money(c.balance),purchases:c.purchases||0,total:money(c.total)}));
 if(source==='cash')return(state.cash||[]).filter(m=>inRange(m.date,config)).map(m=>({date:safeDate(m.date),time:safeTime(m.date),type:m.type==='in'?'Entrada':'Salida',description:m.description,employee:m.employee||'—',income:m.type==='in'?money(m.amount):'—',expense:m.type==='out'?money(m.amount):'—',amount:money(m.amount),client:m.client||'—'}));
 if(source==='stock')return(state.stockMovements||[]).filter(m=>inRange(m.date,config)).map(m=>{const p=(state.products||[]).find(x=>x.id===m.productId);return{date:safeDate(m.date),time:safeTime(m.date),product:p?.name||'Producto eliminado',code:p?.code||'—',type:m.type==='in'?'Entrada':m.type==='out'?'Salida':'Corrección',quantity:Number(m.amount||0).toLocaleString(locale()),reason:m.reason||'—',employee:m.employee||'—'}});
 if(source==='employees')return(state.employees||[]).map(e=>({name:e.name,role:e.role||'—',sales:e.sales||0,total:money(e.total),ticket:money(e.ticket),commission:money(Number(e.total||0)*.01),goal:`${e.goal||0}%`}));
 if(source==='sellerSummary')return sellerRows(config);
 if(source==='cashClosing')return cashClosingRows(context,config);
 if(source==='clientLedger')return clientLedgerRows(context,config).map(stripInternal);
 if(source==='closings')return(state.closings||[]).filter(c=>inRange(c.date,config)).map(c=>({date:safeDate(c.date),opened:safeTime(c.openedAt),closed:safeTime(c.date),employee:c.employee||'—',income:money(c.entries),expense:money(c.exits),total:money(c.total),reason:c.reason||'—'}));
 return[];
}
function summaryFor(model,rows){const label={saleItems:'ítems de la venta',sales:'registros de venta',employeeSales:'ventas del funcionario',products:'productos',clients:'clientes',cash:'movimientos',stock:'movimientos',employees:'funcionarios',sellerSummary:'vendedores',cashClosing:'movimientos de caja',clientLedger:'movimientos del cliente',closings:'cierres',payables:'cuentas',purchases:'compras',fiscal:'documentos'}[model.source]||'registros';return`${rows.length} ${label}`}
function documentKpis(model,rows,context,config){
 if(model.source==='sellerSummary'){const sales=salesInRange(config),total=sum(sales,'total');return[['Ventas',sales.length],['Facturado',money(total)],['Ticket promedio',money(sales.length?total/sales.length:0)],['Mejor vendedor',rows[0]?.name||'—']]}
 if(model.source==='cashClosing'){const movements=cashClosingMovements(context,config),ins=sum(movements.filter(m=>m.type==='in'),'amount'),outs=sum(movements.filter(m=>m.type==='out'),'amount');return[['Movimientos',rows.length],['Entradas',money(ins)],['Salidas',money(outs)],['Saldo esperado',money(ins-outs)]]}
 if(model.source==='clientLedger'){const client=clientFor(context);return[['Cliente',client?.name||'Seleccione un cliente'],['Compras',client?.purchases||0],['Total comprado',money(client?.total||0)],['Saldo actual',money(client?.balance||0)]]}
 if(model.source==='employeeSales'){const employee=employeeFor(context),sales=(state.sales||[]).filter(s=>inRange(s.date,config)&&((employee?.id&&s.employeeId===employee.id)||s.employee===employee?.name)),total=sum(sales,'total');return[['Funcionario',employee?.name||'—'],['Ventas',sales.length],['Facturado',money(total)],['Ticket promedio',money(sales.length?total/sales.length:0)]]}
 if(model.source==='saleItems'){const sale=saleFor(context);return[['Cliente',sale?.client||'Consumidor final'],['Pago',sale?.payment||'—'],['Ítems',sale?.items||rows.length],['Total',money(sale?.total||0)]]}
 return[];
}
function periodText(config){if(!config.dateFrom&&!config.dateTo)return'Todo el historial';if(config.dateFrom===config.dateTo)return config.dateFrom?safeDate(`${config.dateFrom}T12:00:00`):'Todo el historial';return`${config.dateFrom?safeDate(`${config.dateFrom}T12:00:00`):'Inicio'} — ${config.dateTo?safeDate(`${config.dateTo}T12:00:00`):'Hoy'}`}
function documentMeta(model,context){const sale=saleFor(context),generated=context.generatedRecord;if(sale)return{label:'VENTA',number:sale.id||'V000000',date:safeDate(sale.date),time:safeTime(sale.date)};if(generated)return{label:'DOCUMENTO',number:generated.documentNumber||'D000000',date:safeDate(generated.createdAt),time:safeTime(generated.createdAt)};return{label:'DOCUMENTO',number:'Vista previa',date:safeDate(new Date()),time:safeTime(new Date())}}
function contextLine(model,context){const client=clientFor(context),employee=employeeFor(context),sale=saleFor(context);if(sale)return`${sale.client||'Consumidor final'} · ${sale.payment||'—'}`;if(client)return`${client.name} · ${client.document||client.code||'Sin documento'} · ${client.phone||'Sin teléfono'}`;if(employee)return`${employee.name} · ${employee.role||'Funcionario'}`;if(model.source==='cashClosing')return'Detalle de entradas, salidas y saldo acumulado';return''}
const referenceValue=value=>value==null||value===''?'—':String(value);
const referenceClass=(model,config,name)=>`document-sheet reference-document reference-${name} format-${esc(config.format)} style-${esc(config.style)} font-${esc(config.fontSize)}`;
function referenceLogo(config,business){if(!config.showLogo)return'';return business.logo?`<img src="${esc(business.logo)}" alt="Logotipo de ${esc(business.businessName||'la empresa')}">`:`<span class="reference-logo-placeholder">${esc((business.businessName||'G')[0])}</span>`}
function saleClient(sale){return(state.clients||[]).find(client=>client.id===sale?.clientId||client.name===sale?.client)||null}
function saleItemsWithBlanks(sale,minRows=7){const rows=sourceRows('saleItems',{saleId:sale?.uuid||sale?.id},{}),blanks=Array.from({length:Math.max(0,minRows-rows.length)},()=>null);return[...rows,...blanks]}
function referenceArticle(model,config,name,content){return`<article class="${referenceClass(model,config,name)}" style="--doc-accent:${esc(config.accent)}" data-reference-template="${esc(name)}">${content}</article>`}
function closingRange(context,config){const closing=context.closingId?(state.closings||[]).find(item=>item.id===context.closingId):null;return{closing,start:closing?new Date(closing.openedAt||closing.date).getTime():parseBoundary(config.dateFrom),end:closing?new Date(closing.date).getTime():parseBoundary(config.dateTo,true)}}
function referenceCashSales(context,config){const bounds=closingRange(context,config);return(state.sales||[]).filter(sale=>(sale.type||'Venta')==='Venta'&&new Date(sale.date).getTime()>=bounds.start&&new Date(sale.date).getTime()<=bounds.end)}
function cashPaymentSummary(sales,movements){const methods=['Efectivo','PIX','QR','Transferencia'],manual=movements.filter(movement=>!/^Venta\b/i.test(String(movement.description||''))),sangria=sum(manual.filter(movement=>movement.type==='out'),'amount'),supplement=sum(manual.filter(movement=>movement.type==='in'&&!/^Pago\b/i.test(String(movement.description||''))),'amount');return methods.map(method=>{const sold=sum(sales.filter(sale=>sale.payment===method),'total'),cashMethod=method==='Efectivo';return{method,sales:sold,returns:0,sangria:cashMethod?sangria:0,supplement:cashMethod?supplement:0,total:sold-(cashMethod?sangria:0)+(cashMethod?supplement:0)}})}
function cashTransactionRows(sales,movements){const saleRows=sales.map(sale=>({date:sale.date,number:sale.id,type:'Venta',description:sale.client||'Consumidor final',discount:Number(sale.discountTotal||0),total:Number(sale.total||0),payment:sale.payment||'—',notes:sale.notes||sale.delivery||'—'})),movementRows=movements.filter(movement=>!/^Venta\b/i.test(String(movement.description||''))).map(movement=>({date:movement.date,number:movement.id,type:movement.type==='in'?'Entrada':'Salida',description:movement.description||'Movimiento de caja',discount:0,total:Number(movement.amount||0),payment:'Efectivo',notes:movement.employee||'—'}));return[...saleRows,...movementRows].sort((a,b)=>new Date(a.date)-new Date(b.date))}
function cashSummarySheetHtml(model,config,context){
 const business=state.settings||{},bounds=closingRange(context,config),closing=bounds.closing,movements=cashClosingMovements(context,config),sales=referenceCashSales(context,config),payments=cashPaymentSummary(sales,movements),transactions=cashTransactionRows(sales,movements),receivedSales=sum(sales.filter(sale=>sale.payment!=='Cuenta cliente'),'total'),debitedSales=sales.filter(sale=>sale.payment==='Cuenta cliente'),debitedValue=sum(debitedSales,'total'),debtPayments=sum(movements.filter(movement=>/^Pago\b/i.test(String(movement.description||''))),'amount'),ins=sum(movements.filter(movement=>movement.type==='in'),'amount'),outs=sum(movements.filter(movement=>movement.type==='out'),'amount'),initial=Number(closing?.initialBalance||0),expected=initial+ins-outs,reported=closing?.reportedBalance??closing?.reported??null,difference=reported==null?null:Number(reported)-expected,openedAt=closing?.openedAt||state.cashSession?.openedAt||config.dateFrom,closedAt=closing?.date||state.cashSession?.closedAt||config.dateTo;
 const financial=[['Ventas realizadas',`${sales.length} · ${money(sum(sales,'total'))}`],['Ventas debitadas',`${debitedSales.length} · ${money(debitedValue)}`],['Ventas recibidas',money(receivedSales)],['Débitos pagados',money(debtPayments)],['Total recibido',money(receivedSales+debtPayments)]];
 const balances=[['Saldo inicial',money(initial)],['Valores recibidos',money(ins)],['Salidas / sangrías',money(outs)],['Saldo final esperado',money(expected)],['Saldo informado',reported==null?'No informado':money(reported)],['Diferencia de caja',difference==null?'—':money(difference)]];
 return referenceArticle(model,config,'cash',`<header class="reference-centered-header">${referenceLogo(config,business)}<div><h1>${esc(business.businessName||'GRASSI Repuestos')}</h1><span>${esc(business.legalName||'')}</span></div></header><section class="reference-cash-meta"><b>Caja n.º ${esc(closing?.id||state.cashSession?.id||'Vista previa')}</b><span><strong>Inicio:</strong> ${esc(referenceValue(openedAt?safeDate(openedAt)+' '+safeTime(openedAt):''))}</span><span><strong>Término:</strong> ${esc(referenceValue(closedAt?safeDate(closedAt)+' '+safeTime(closedAt):''))}</span><span><strong>Abierto por:</strong> ${esc(closing?.openedBy||state.cashSession?.openedBy||'—')}</span><span><strong>Cerrado por:</strong> ${esc(closing?.employee||state.cashSession?.closedBy||'—')}</span></section><section class="reference-financial-grid"><div><h2>Resumen financiero</h2>${financial.map(([label,value])=>`<p><strong>${esc(label)}</strong><span>${esc(value)}</span></p>`).join('')}</div><div><h2>Saldo de caja</h2>${balances.map(([label,value])=>`<p><strong>${esc(label)}</strong><span>${esc(value)}</span></p>`).join('')}</div></section><section class="reference-section"><h2>Total por medio de pago</h2><table class="reference-grid-table"><thead><tr><th>Medio de pago</th><th>Ventas</th><th>Devoluciones</th><th>Sangría</th><th>Suplemento</th><th>Total</th></tr></thead><tbody>${payments.map(row=>`<tr><td>${esc(row.method)}</td><td>${money(row.sales)}</td><td>${money(row.returns)}</td><td>${money(row.sangria)}</td><td>${money(row.supplement)}</td><td><strong>${money(row.total)}</strong></td></tr>`).join('')}<tr class="reference-total-row"><td>TOTAL</td><td>${money(sum(payments,'sales'))}</td><td>${money(sum(payments,'returns'))}</td><td>${money(sum(payments,'sangria'))}</td><td>${money(sum(payments,'supplement'))}</td><td>${money(sum(payments,'total'))}</td></tr></tbody></table></section><section class="reference-section"><h2>Resumen / transacciones</h2><table class="reference-grid-table reference-transactions"><thead><tr><th>N.º trans.</th><th>Fecha y hora</th><th>Tipo</th><th>Cliente / descripción</th><th>Descuento</th><th>Total final</th><th>Pago</th><th>Observaciones</th></tr></thead><tbody>${transactions.map(row=>`<tr><td>${esc(row.number)}</td><td>${safeDate(row.date)}<br><small>${safeTime(row.date)}</small></td><td>${esc(row.type)}</td><td>${esc(row.description)}</td><td>${money(row.discount)}</td><td>${money(row.total)}</td><td>${esc(row.payment)}</td><td>${esc(row.notes)}</td></tr>`).join('')||'<tr><td colspan="8">Sin movimientos en el período.</td></tr>'}</tbody></table></section><div class="reference-signature-row"><span>Responsable de caja</span><span>Supervisor</span></div><footer>${esc(config.footer||'Resumen generado por GRASSI PDV & ERP')}</footer>`)}
function classicSaleReceiptSheetHtml(model,config,context){
 const sale=saleFor(context),business=state.settings||{},client=saleClient(sale),meta=documentMeta(model,context),items=saleItemsWithBlanks(sale,8),total=Number(sale?.total||0),debit=sale?.payment==='Cuenta cliente'?total:0;
 const left=[['Nome / Razão Social',sale?.client||'Consumidor final'],['Endereço',client?.address],['CEP',client?.postalCode],['RG / Insc. Estadual',client?.stateRegistration],['CPF / CNPJ',client?.document]];
 const right=[['Bairro',client?.zone||client?.neighborhood],['Estado',client?.state],['Cidade',client?.city],['Celular',client?.phone],['Telefone',client?.telephone],['E-mail',client?.email]];
 return referenceArticle(model,config,'receipt',`<header class="reference-receipt-header"><div class="reference-receipt-logo">${referenceLogo(config,business)}</div><div class="reference-receipt-business"><h1>${esc(business.businessName||'GRASSI Repuestos')}</h1><p><b>NIT:</b> ${esc(referenceValue(business.nit))}</p><p><b>Dirección:</b> ${esc(referenceValue(business.address))}</p><p><b>E-mail:</b> ${esc(referenceValue(business.email))}</p></div><div class="reference-receipt-number"><b>Venda</b><span>Data / Hora da Transação</span><strong>${esc(meta.date)} · ${esc(meta.time)}</strong><span>N. Transação</span><strong>${esc(meta.number)}</strong></div></header><section class="reference-client-box reference-sale-client"><h2>DADOS DO CLIENTE</h2><div class="reference-sale-client-columns"><div>${left.map(([label,value])=>`<p><b>${esc(label)}:</b> ${esc(referenceValue(value))}</p>`).join('')}</div><div>${right.map(([label,value])=>`<p><b>${esc(label)}:</b> ${esc(referenceValue(value))}</p>`).join('')}</div></div></section><section class="reference-section"><table class="reference-grid-table reference-items"><thead><tr><th>CÓDIGO</th><th>DESCRIÇÃO</th><th>QUANTIDADE</th><th>PREÇO UNITÁRIO</th><th>VALOR</th></tr></thead><tbody>${items.map(item=>item?`<tr><td>${esc(item.code)}</td><td>${esc(item.product)}</td><td>${esc(item.quantity)}</td><td>${esc(item.unitPrice)}</td><td>${esc(item.total)}</td></tr>`:'<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody><tfoot><tr><td colspan="3"></td><th>Total a Pagar</th><td>${money(total)}</td></tr><tr><td colspan="3"></td><th>Valor Debitado</th><td>${money(debit)}</td></tr></tfoot></table></section><section class="reference-order-signature"><span><b>PEDIDOS AL CEL.:</b> ${esc(referenceValue(business.phone))}</span><span>FIRMA DEL CLIENTE</span></section><p class="reference-seller-line">Vendedor: <b>${esc(referenceValue(sale?.employee))}</b></p><p class="reference-annotation-line">Assinatura / anotações</p><footer>${esc(config.footer||'Comprobante comercial de venta. No sustituye una factura fiscal homologada por el SIN.')}</footer>`)}
function modernSaleReceiptSheetHtml(model,config,context){
 const sale=saleFor(context),business=state.settings||{},client=saleClient(sale),meta=documentMeta(model,context),items=saleItemsWithBlanks(sale),total=Number(sale?.total||0),debit=sale?.payment==='Cuenta cliente'?total:0;
 return referenceArticle(model,config,'receipt',`<header class="reference-receipt-header"><div class="reference-receipt-logo">${referenceLogo(config,business)}</div><div class="reference-receipt-business"><h1>${esc(business.businessName||'GRASSI Repuestos')}</h1><p><b>NIT:</b> ${esc(referenceValue(business.nit))}</p><p><b>Dirección:</b> ${esc(referenceValue(business.address))}</p><p><b>E-mail:</b> ${esc(referenceValue(business.email))} <b>Tel.:</b> ${esc(referenceValue(business.phone))}</p></div><div class="reference-receipt-number"><b>VENTA</b><span>Fecha / hora</span><strong>${esc(meta.date)} · ${esc(meta.time)}</strong><span>N.º transacción</span><strong>${esc(meta.number)}</strong></div></header><section class="reference-client-box"><h2>DATOS DEL CLIENTE</h2><div><p class="wide"><b>Nombre / razón social:</b> ${esc(sale?.client||'Consumidor final')}</p><p><b>Ciudad:</b> ${esc(referenceValue(client?.city))}</p><p><b>CI / NIT:</b> ${esc(referenceValue(client?.document))}</p><p><b>Teléfono / celular:</b> ${esc(referenceValue(client?.phone))}</p><p class="wide"><b>Observaciones:</b> ${esc(referenceValue(client?.notes||sale?.notes))}</p></div></section><section class="reference-section"><table class="reference-grid-table reference-items"><thead><tr><th>Código</th><th>Descripción</th><th>Cantidad</th><th>Precio unitario</th><th>Valor</th></tr></thead><tbody>${items.map(item=>item?`<tr><td>${esc(item.code)}</td><td>${esc(item.product)}</td><td>${esc(item.quantity)}</td><td>${esc(item.unitPrice)}</td><td>${esc(item.total)}</td></tr>`:'<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody><tfoot><tr><td colspan="3"></td><th>Total a pagar</th><td>${money(total)}</td></tr><tr><td colspan="3"></td><th>Valor debitado</th><td>${money(debit)}</td></tr></tfoot></table></section><section class="reference-receipt-notes"><span><b>Pedidos al celular:</b> ${esc(referenceValue(business.phone))}</span><span><b>Medio de pago:</b> ${esc(referenceValue(sale?.payment))}</span><span><b>Vendedor:</b> ${esc(referenceValue(sale?.employee))}</span></section><div class="reference-signature-row"><span>Firma del cliente</span><span>Firma del vendedor</span></div><footer>${esc(config.footer||'Comprobante comercial de venta. No sustituye una factura fiscal homologada por el SIN.')}</footer>`)}
function saleReceiptSheetHtml(model,config,context){return state.settings?.saleReceiptTemplate==='modern'?modernSaleReceiptSheetHtml(model,config,context):classicSaleReceiptSheetHtml(model,config,context)}
const smallNumbers=['cero','uno','dos','tres','cuatro','cinco','seis','siete','ocho','nueve','diez','once','doce','trece','catorce','quince','dieciséis','diecisiete','dieciocho','diecinueve','veinte','veintiuno','veintidós','veintitrés','veinticuatro','veinticinco','veintiséis','veintisiete','veintiocho','veintinueve'];
function numberWordsUnderThousand(value){const n=Math.floor(value);if(n<30)return smallNumbers[n];if(n<100){const tens=['','','','treinta','cuarenta','cincuenta','sesenta','setenta','ochenta','noventa'],unit=n%10;return`${tens[Math.floor(n/10)]}${unit?` y ${smallNumbers[unit]}`:''}`}if(n===100)return'cien';const hundreds=['','ciento','doscientos','trescientos','cuatrocientos','quinientos','seiscientos','setecientos','ochocientos','novecientos'],rest=n%100;return`${hundreds[Math.floor(n/100)]}${rest?` ${numberWordsUnderThousand(rest)}`:''}`}
function numberWordsEs(value){const n=Math.max(0,Math.floor(Number(value)||0));if(n<1000)return numberWordsUnderThousand(n);if(n<1000000){const thousands=Math.floor(n/1000),rest=n%1000;return`${thousands===1?'mil':`${numberWordsUnderThousand(thousands)} mil`}${rest?` ${numberWordsUnderThousand(rest)}`:''}`}const millions=Math.floor(n/1000000),rest=n%1000000;return`${millions===1?'un millón':`${numberWordsEs(millions)} millones`}${rest?` ${numberWordsEs(rest)}`:''}`}
function amountWords(value){const amount=Math.max(0,Number(value)||0),integer=Math.floor(amount),cents=Math.round((amount-integer)*100);return`${numberWordsEs(integer)} ${String(cents).padStart(2,'0')}/100 Bolivianos`}
function zonaFrancaSheetHtml(model,config,context){
 const sale=saleFor(context),business=state.settings||{},client=saleClient(sale),meta=documentMeta(model,context),items=saleItemsWithBlanks(sale),subtotal=Number(sale?.subtotal??sale?.total??0),discount=Number(sale?.discountTotal||0),total=Number(sale?.total||0),authorization=business.authorizationCode||'No configurado',pointOfSale=business.pointOfSale||'—';
 return referenceArticle(model,config,'zona',`<header class="reference-zona-header"><div class="reference-zona-logo">${referenceLogo(config,business)}</div><div class="reference-zona-business"><h1>${esc(business.businessName||'GRASSI Repuestos')}</h1><p>${esc(business.legalName||'Matriz / Sucursal')}</p><p><b>Punto de venta:</b> ${esc(pointOfSale)}</p><p><b>Dirección:</b> ${esc(referenceValue(business.address))}</p><p><b>Zona / barrio:</b> ${esc(referenceValue(business.zone))}</p><p><b>Teléfono:</b> ${esc(referenceValue(business.phone))} · ${esc(referenceValue(business.city))}</p></div><div class="reference-zona-fiscal"><p><b>NIT</b><span>${esc(referenceValue(business.nit))}</span></p><p><b>FACTURA N.º</b><span>${esc(meta.number)}</span></p><p><b>CÓD. AUTORIZACIÓN</b><span>${esc(authorization)}</span></p></div></header><section class="reference-zona-title"><h2>FACTURA DE VENTA DE ZONA FRANCA</h2><p>Sin derecho a crédito fiscal</p><strong>MODELO COMERCIAL · REQUIERE HOMOLOGACIÓN DEL SIN PARA VALIDEZ FISCAL</strong></section><section class="reference-zona-client"><p><b>Fecha:</b> ${esc(meta.date)} · ${esc(meta.time)}</p><p><b>NIT / CI / CEX:</b> ${esc(referenceValue(client?.document))}</p><p><b>Nombre / razón social:</b> ${esc(sale?.client||'Consumidor final')}</p><p><b>Cód. cliente:</b> ${esc(referenceValue(client?.code))}</p></section><section class="reference-section"><table class="reference-grid-table reference-zona-items"><thead><tr><th>Código producto</th><th>Cantidad</th><th>Descripción</th><th>Unidad medida</th><th>Precio unitario</th><th>Descuento</th><th>Subtotal</th></tr></thead><tbody>${items.map(item=>item?`<tr><td>${esc(item.code)}</td><td>${esc(item.quantity)}</td><td>${esc(item.product)}</td><td>${esc(item.unit)}</td><td>${esc(item.unitPrice)}</td><td>${esc(item.discount)}</td><td>${esc(item.total)}</td></tr>`:'<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td><td></td></tr>').join('')}</tbody><tfoot><tr><td colspan="5"></td><th>SUBTOTAL</th><td>${money(subtotal)}</td></tr><tr><td colspan="5"></td><th>DESCUENTO</th><td>${money(discount)}</td></tr><tr><td colspan="5"></td><th>MONTO A PAGAR</th><td>${money(total)}</td></tr></tfoot></table></section><p class="reference-amount-words"><b>Son:</b> ${esc(amountWords(total))}</p><section class="reference-zona-footer"><div><p>Este modelo reproduce el formato comercial de una factura de Zona Franca.</p><p>La emisión fiscal, autorización, leyenda y QR deben provenir de una integración homologada con el Servicio de Impuestos Nacionales.</p></div><span class="reference-qr-placeholder">QR FISCAL<br><small>Disponible al integrar SIN</small></span></section><footer>${esc(config.footer||'Documento comercial generado por GRASSI PDV & ERP')}</footer>`)}
function sheetHtml(model,config,context=studio.context){
 if(model.id==='cash-closing')return cashSummarySheetHtml(model,config,context);
 if(model.id==='sale-receipt')return saleReceiptSheetHtml(model,config,context);
 if(model.id==='zona-franca-invoice')return zonaFrancaSheetHtml(model,config,context);
 const rows=sourceRows(model.source,context,config),selected=(config.fields||model.defaultFields).filter(key=>fieldSets[model.source]?.some(([id])=>id===key)),fields=selected.length?selected:model.defaultFields.slice(0,4),sample=rows.slice(0,config.format==='label'?1:500),meta=documentMeta(model,context),kpis=documentKpis(model,rows,context,config),business=state.settings||{},logo=config.showLogo?(business.logo?`<img src="${esc(business.logo)}" alt="Logotipo">`:`<i>${esc((business.businessName||'G')[0])}</i>`):'';
 return`<article class="document-sheet format-${esc(config.format)} style-${esc(config.style)} font-${esc(config.fontSize)}" style="--doc-accent:${esc(config.accent)}"><header class="document-company-header"><div class="document-logo-cell">${logo}</div><div class="document-business-cell">${config.showBusiness?`<strong>${esc(business.businessName||'GRASSI Repuestos')}</strong>${business.legalName?`<span>${esc(business.legalName)}</span>`:''}<small>${esc([business.nit&&`NIT ${business.nit}`,[business.address,business.city,business.postalCode].filter(Boolean).join(' · '),business.phone,business.email].filter(Boolean).join(' · '))}</small>`:''}</div><div class="document-transaction-cell"><small>${esc(meta.label)}</small><strong>${esc(meta.number)}</strong><span>${esc(meta.date)} · ${esc(meta.time)}</span></div></header><section class="document-title"><div><small>GRASSI · PDV & ERP</small><h2>${esc(config.title)}</h2>${contextLine(model,context)?`<p>${esc(contextLine(model,context))}</p>`:''}</div>${config.showPeriod?`<span>Período<br><b>${esc(periodText(config))}</b></span>`:''}</section>${kpis.length?`<div class="document-kpis">${kpis.map(([label,value])=>`<div><span>${esc(label)}</span><strong>${esc(value)}</strong></div>`).join('')}</div>`:''}<div class="document-table-wrap"><table><thead><tr>${fields.map(key=>`<th>${esc(fieldLabel(model.source,key))}</th>`).join('')}</tr></thead><tbody>${sample.map(row=>`<tr>${fields.map(key=>`<td>${esc(row[key]??'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${fields.length}">Sin datos registrados en el período seleccionado.</td></tr>`}</tbody></table></div><div class="document-summary"><span>${esc(summaryFor(model,rows))}</span><b>Generado ${safeDate(new Date())} · ${safeTime(new Date())}</b></div>${config.showSignature?'<div class="document-signatures"><span>Responsable</span><span>Cliente / receptor</span></div>':''}<footer>${esc(config.footer||'')}</footer></article>`;
}
function editorConfig(form){const data=new FormData(form),model=modelById(form.dataset.id);return{title:data.get('title')||model.title,format:data.get('format')||model.allowedFormats[0],style:'official',accent:'#111111',fontSize:data.get('fontSize')||'medium',dateFrom:data.get('dateFrom')||'',dateTo:data.get('dateTo')||'',showLogo:data.has('showLogo'),showBusiness:data.has('showBusiness'),showPeriod:data.has('showPeriod'),showSignature:data.has('showSignature'),footer:data.get('footer')||'',fields:data.getAll('fields')}}
function updatePreview(form){const model=modelById(form?.dataset.id),preview=form?.querySelector('[data-document-preview]');if(model&&preview)preview.innerHTML=sheetHtml(model,editorConfig(form))}
function contextPicker(type,modelId){const entries=type==='sale'?(state.sales||[]):type==='employee'?(state.employees||[]):(state.clients||[]),labels={sale:'Seleccione una venta',employee:'Seleccione un funcionario',client:'Seleccione un cliente'};openLayer(`${layerHead(labels[type])}<div class="layer-body"><div class="data-region"><table class="data-table"><thead><tr><th>${type==='sale'?'Venta':type==='employee'?'Funcionario':'Cliente'}</th><th>${type==='sale'?'Fecha':type==='employee'?'Cargo':'Documento'}</th><th>${type==='sale'?'Total':type==='employee'?'Ventas':'Saldo'}</th><th></th></tr></thead><tbody>${entries.map(entry=>{const id=entry.uuid||entry.id,name=type==='sale'?entry.id:entry.name,second=type==='sale'?safeDate(entry.date):type==='employee'?(entry.role||'—'):(entry.document||entry.code||'—'),third=type==='sale'?money(entry.total):type==='employee'?(entry.sales||0):money(entry.balance);return`<tr><td><strong>${esc(name)}</strong></td><td>${esc(second)}</td><td>${esc(third)}</td><td><button class="table-action" data-doc-pick="${esc(type)}" data-doc-pick-id="${esc(id)}">${svg('receipt')} Generar</button></td></tr>`}).join('')||'<tr><td colspan="4">Todavía no hay registros.</td></tr>'}</tbody></table></div></div><footer class="layer-foot"><button class="btn" data-action="close-layer">Cancelar</button></footer>`,'modal');studio.pendingModel=modelId}
function openEditor(id,context={}){const model=modelById(id);if(!model)return;if(model.contextType&&!context[`${model.contextType}Id`])return contextPicker(model.contextType,model.id);studio.context={...context};const config=configFor(model),fields=fieldSets[model.source]||[],showDates=datedSources.has(model.source);openLayer(`${layerHead('Editor de documento')}<form id="documentTemplateForm" data-id="${model.id}"><div class="layer-body document-editor"><aside class="document-controls"><div class="field"><label>Nombre del modelo</label><input name="title" value="${esc(config.title)}"></div><div class="form-grid"><div class="field"><label>Formato</label><select name="format">${model.allowedFormats.map(id=>`<option value="${id}" ${config.format===id?'selected':''}>${formats[id]}</option>`).join('')}</select></div><input type="hidden" name="style" value="official">${showDates?`<div class="field"><label>Fecha inicial</label><input name="dateFrom" type="date" value="${esc(config.dateFrom)}"></div><div class="field"><label>Fecha final</label><input name="dateTo" type="date" value="${esc(config.dateTo)}"></div>`:''}<input type="hidden" name="accent" value="#111111"><div class="field"><label>Tamaño del texto</label><select name="fontSize">${[['small','Pequeño'],['medium','Mediano'],['large','Grande']].map(([id,label])=>`<option value="${id}" ${config.fontSize===id?'selected':''}>${label}</option>`).join('')}</select></div></div><div class="document-switches">${[['showLogo','Mostrar logotipo'],['showBusiness','Datos de la empresa'],['showPeriod','Fecha y período'],['showSignature','Espacio para firmas']].map(([name,label])=>`<label><input type="checkbox" name="${name}" ${config[name]?'checked':''}><span>${label}</span></label>`).join('')}</div><div class="field"><label>Campos y columnas</label><div class="document-field-list">${fields.map(([key,label])=>`<label><input type="checkbox" name="fields" value="${key}" ${config.fields.includes(key)?'checked':''}><span>${esc(label)}</span></label>`).join('')}</div></div><div class="field"><label>Texto del pie</label><textarea name="footer" rows="3">${esc(config.footer)}</textarea></div><button type="button" class="btn secondary" data-doc-reset="${model.id}">Restaurar modelo original</button></aside><main class="document-preview" data-document-preview>${sheetHtml(model,config,context)}</main></div><footer class="layer-foot"><button type="button" class="btn" data-doc-cancel>Cancelar</button><button type="button" class="btn secondary" data-doc-print>${svg('receipt')} Imprimir / PDF</button><button class="btn primary" type="submit" data-doc-generate>${svg('check')} Generar y guardar</button></footer></form>`,'modal document-template-modal')}
function returnFromEditor(){if(studio.context.returnTo==='pos-client')return globalThis.posClientPicker?.();if(studio.context.returnTo==='client-profile')return globalThis.clientAccount?.(studio.context.clientId,false);if(studio.context.returnTo==='employee-profile')return globalThis.employeeProfile?.(studio.context.employeeId);if(studio.context.returnTo==='sale-view')return globalThis.saleView?.(studio.context.saleId);closeLayer()}
function nextLocalDocumentNumber(){const values=ensureGenerated().map(item=>Number(String(item.documentNumber||'').replace(/\D/g,''))).filter(Number.isFinite);return`D${String(values.length?Math.max(...values)+1:0).padStart(6,'0')}`}
async function generateDocument(form){const model=modelById(form.dataset.id),config=editorConfig(form),now=new Date().toISOString(),clientDocumentId=globalThis.crypto?.randomUUID?.()||`doc-${Date.now()}`,sourceId=studio.context.saleId||studio.context.clientId||studio.context.employeeId||studio.context.closingId||null,record={clientDocumentId,documentNumber:nextLocalDocumentNumber(),documentType:model.id,title:config.title,sourceType:model.contextType||model.source,sourceId,periodStart:config.dateFrom||null,periodEnd:config.dateTo||null,createdAt:now,createdBy:state.user?.id||null,snapshot:{config,context:{...studio.context},rows:sourceRows(model.source,studio.context,config)}};ensureGenerated().unshift(record);ensureSettings()[model.id]=config;save();try{const saved=await globalThis.GrassiBackend?.saveGeneratedDocument?.(record);if(saved?.documentNumber)record.documentNumber=saved.documentNumber;if(saved?.id)record.id=saved.id;record.syncStatus='synced'}catch(error){record.syncStatus='pending';console.warn('Documento pendiente de sincronización',error)}save();return record}
function render(){ensureSettings();const categories=['Todos',...new Set(models.map(model=>model.category))],visible=models.filter(model=>studio.category==='Todos'||model.category===studio.category),generated=ensureGenerated().slice(0,50);return`<section class="page page-documents">${pageHeader('Documentos y modelos',models.length)}<div class="page-body"><div class="document-hero"><div><p class="eyebrow">CENTRO DE DOCUMENTOS</p><h2>Informes estructurados, filtrables y guardados</h2><p>Genere tablas por período, venta, cliente o funcionario. Cada documento conserva una copia de los datos utilizados.</p></div><span>${svg('receipt')}<b>${models.length}</b><small>modelos</small></span></div><div class="document-category-strip">${categories.map(category=>`<button class="${studio.category===category?'active':''}" data-doc-category="${esc(category)}">${esc(category)} <b>${category==='Todos'?models.length:models.filter(model=>model.category===category).length}</b></button>`).join('')}</div><div class="document-model-grid">${visible.map(model=>{const config=configFor(model);return`<article class="document-model-card"><header><span>${svg(model.icon)}</span><small>${esc(model.category)}</small></header><h3>${esc(config.title)}</h3><p>${esc(formats[config.format])} · ${esc(styles[config.style])}</p><div>${model.allowedFormats.map(id=>`<i>${esc(formats[id].replace('Térmico ','').replace(' mm','mm'))}</i>`).join('')}</div><footer><button class="btn secondary" data-doc-export="${model.id}" title="Exportar configuración">${svg('download')}</button><button class="btn primary" data-doc-template="${model.id}">Editar y generar</button></footer></article>`}).join('')}</div>${generated.length?`<section class="generated-documents"><div class="section-title"><div><p class="eyebrow">HISTORIAL</p><h2>Documentos generados</h2></div><span class="count">${generated.length}</span></div><div class="data-region"><table class="data-table"><thead><tr><th>Número</th><th>Documento</th><th>Período</th><th>Generado</th><th>Estado</th></tr></thead><tbody>${generated.map(item=>`<tr><td><strong>${esc(item.documentNumber||'D000000')}</strong></td><td>${esc(item.title||item.documentType)}</td><td>${esc(periodText({dateFrom:item.periodStart,dateTo:item.periodEnd}))}</td><td>${safeDate(item.createdAt)} · ${safeTime(item.createdAt)}</td><td><span class="status ${item.syncStatus==='pending'?'warning':'success'}">${item.syncStatus==='pending'?'Pendiente':'Guardado'}</span></td></tr>`).join('')}</tbody></table></div></section>`:''}</div></section>`}
document.addEventListener('click',event=>{const directClient=event.target.closest('[data-doc-client-statement]');if(directClient)return openEditor('client-statement',{clientId:directClient.dataset.docClientStatement,returnTo:directClient.dataset.docReturn||''});const directEmployee=event.target.closest('[data-doc-employee-report]');if(directEmployee)return openEditor('employee-performance',{employeeId:directEmployee.dataset.docEmployeeReport,returnTo:directEmployee.dataset.docReturn||''});const directSale=event.target.closest('[data-doc-sale-report]');if(directSale)return openEditor('sale-report',{saleId:directSale.dataset.docSaleReport,returnTo:directSale.dataset.docReturn||''});const saleReceipt=event.target.closest('[data-doc-sale-receipt]');if(saleReceipt)return openEditor('sale-receipt',{saleId:saleReceipt.dataset.docSaleReceipt,returnTo:saleReceipt.dataset.docReturn||''});const zonaInvoice=event.target.closest('[data-doc-zona-invoice]');if(zonaInvoice)return openEditor('zona-franca-invoice',{saleId:zonaInvoice.dataset.docZonaInvoice,returnTo:zonaInvoice.dataset.docReturn||''});const cashClosing=event.target.closest('[data-doc-cash-closing]');if(cashClosing)return openEditor('cash-closing',{closingId:cashClosing.dataset.docCashClosing||''});const picked=event.target.closest('[data-doc-pick]');if(picked){const type=picked.dataset.docPick,key=`${type}Id`;return openEditor(studio.pendingModel,{[key]:picked.dataset.docPickId})}const cancel=event.target.closest('[data-doc-cancel]');if(cancel)return returnFromEditor();const category=event.target.closest('[data-doc-category]');if(category){studio.category=category.dataset.docCategory;return globalThis.render?.()}const open=event.target.closest('[data-doc-template]');if(open)return openEditor(open.dataset.docTemplate);const reset=event.target.closest('[data-doc-reset]');if(reset){delete ensureSettings()[reset.dataset.docReset];save();return openEditor(reset.dataset.docReset,studio.context)}const print=event.target.closest('[data-doc-print]');if(print){document.body.classList.add('printing-document');window.print();return}const exportButton=event.target.closest('[data-doc-export]');if(exportButton){const model=modelById(exportButton.dataset.docExport),config=configFor(model);return download(`modelo-${model.id}.json`,JSON.stringify({model:model.id,config},null,2),'application/json')}});
document.addEventListener('input',event=>{const form=event.target.closest('#documentTemplateForm');if(form)updatePreview(form)});
document.addEventListener('change',event=>{const form=event.target.closest('#documentTemplateForm');if(form)updatePreview(form)});
document.addEventListener('submit',async event=>{const form=event.target.closest('#documentTemplateForm');if(!form)return;event.preventDefault();event.stopImmediatePropagation();const button=form.querySelector('[data-doc-generate]');if(button)button.disabled=true;try{const model=modelById(form.dataset.id),config=editorConfig(form),record=await generateDocument(form);studio.context={...studio.context,generatedRecord:record};const preview=form.querySelector('[data-document-preview]');if(preview)preview.innerHTML=sheetHtml(model,config,studio.context);if(button)button.innerHTML=`${svg('check')} Guardado ${esc(record.documentNumber)}`;auditEvent('Documento generado','Documentos',`${record.documentNumber} · ${record.title}`,'success');toast(`Documento ${record.documentNumber} guardado. Ya puede imprimirlo o exportarlo a PDF.`)}catch(error){if(button)button.disabled=false;toast(error.message||'No fue posible guardar el documento','error')}},true);
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-document'));
window.GrassiDocuments={render,openEditor,previewHtml:(modelId,context={},overrides={})=>{const model=modelById(modelId);return model?sheetHtml(model,{...configFor(model),...overrides},context):''},openClientStatement:(clientId,returnTo='')=>openEditor('client-statement',{clientId,returnTo}),openEmployeeReport:(employeeId,returnTo='')=>openEditor('employee-performance',{employeeId,returnTo}),openSaleReport:(saleId,returnTo='')=>openEditor('sale-report',{saleId,returnTo}),openSaleReceipt:(saleId,returnTo='')=>openEditor('sale-receipt',{saleId,returnTo}),openZonaFrancaInvoice:(saleId,returnTo='')=>openEditor('zona-franca-invoice',{saleId,returnTo}),openCashClosing:closingId=>openEditor('cash-closing',{closingId}),models};
})();
