(()=>{
const studio={category:'Todos'};
const formats={a4:'A4 vertical',landscape:'A4 horizontal',thermal80:'Térmico 80 mm',thermal58:'Térmico 58 mm',label:'Etiqueta'};
const styles={modern:'Moderno',classic:'Clásico',compact:'Compacto',minimal:'Minimalista'};
const fieldSets={
 sales:[['number','Número'],['date','Fecha'],['time','Hora'],['client','Cliente'],['seller','Vendedor'],['payment','Pago'],['kind','Tipo'],['items','Ítems'],['subtotal','Subtotal'],['discount','Descuento'],['total','Total']],
 products:[['code','Código'],['name','Producto'],['category','Categoría'],['unit','Unidad'],['stock','Stock'],['minimum','Mínimo'],['cost','Costo'],['price','Precio'],['wholesale','Mayorista'],['supplier','Proveedor'],['profit','Margen']],
 clients:[['code','Código'],['name','Cliente'],['type','Tipo'],['document','CI / NIT'],['phone','Teléfono'],['city','Ciudad'],['balance','Saldo'],['purchases','Compras'],['total','Total comprado']],
 cash:[['date','Fecha'],['time','Hora'],['client','Cliente'],['type','Tipo'],['description','Descripción'],['employee','Funcionario'],['income','Entrada'],['expense','Salida'],['amount','Valor']],
 stock:[['date','Fecha'],['time','Hora'],['product','Producto'],['code','Código'],['type','Movimiento'],['quantity','Cantidad'],['reason','Motivo'],['employee','Funcionario']],
 employees:[['name','Funcionario'],['role','Cargo'],['sales','Ventas'],['total','Facturado'],['ticket','Ticket promedio'],['commission','Comisión'],['goal','Meta']],
 closings:[['date','Fecha'],['opened','Apertura'],['closed','Cierre'],['employee','Funcionario'],['income','Entradas'],['expense','Salidas'],['total','Saldo'],['reason','Motivo']],
 payables:[['due','Vencimiento'],['description','Descripción'],['supplier','Proveedor'],['status','Estado'],['amount','Valor']],
 purchases:[['date','Fecha'],['document','Documento'],['supplier','Proveedor'],['product','Producto'],['quantity','Cantidad'],['cost','Costo'],['total','Total']],
 fiscal:[['date','Fecha'],['number','Número'],['model','Modelo'],['client','Cliente'],['cfop','CFOP'],['status','Estado'],['total','Total']]
};
const models=[
 ['sale-receipt','Comprobante de venta','Documentos','sales',['thermal80','thermal58','a4'],['number','date','client','payment','items','discount','total'],'receipt'],
 ['budget','Presupuesto / cotización','Documentos','sales',['a4','thermal80'],['number','date','client','seller','items','subtotal','discount','total'],'receipt'],
 ['order','Pedido de venta','Documentos','sales',['a4','thermal80'],['number','date','client','seller','payment','items','total'],'receipt'],
 ['payment-receipt','Recibo de pago','Documentos','cash',['a4','thermal80','thermal58'],['date','client','description','employee','amount'],'cash'],
 ['cash-closing','Cierre de caja','Documentos','closings',['a4','thermal80'],['date','opened','closed','employee','income','expense','total'],'wallet'],
 ['product-label','Etiqueta de producto y precio','Documentos','products',['label','thermal58','thermal80'],['code','name','price'],'tag'],
 ['price-list','Lista de precios','Documentos','products',['a4','landscape'],['code','name','unit','price','wholesale'],'tag'],
 ['stock-count','Hoja de inventario físico','Documentos','products',['a4','landscape'],['code','name','category','unit','stock'],'box'],
 ['client-statement','Estado de cuenta del cliente','Documentos','clients',['a4','thermal80'],['code','name','document','balance','purchases','total'],'users'],
 ['client-file','Ficha del cliente','Documentos','clients',['a4'],['code','name','type','document','phone','city','balance'],'users'],
 ['product-file','Ficha del producto','Documentos','products',['a4'],['code','name','category','unit','stock','cost','price','wholesale','supplier'],'box'],
 ['revenue','Faturamiento','Ventas','sales',['a4','landscape'],['date','number','client','seller','total'],'chart'],
 ['sales-count','Cantidad de ventas','Ventas','sales',['a4','landscape'],['date','number','kind','items','total'],'chart'],
 ['average-ticket','Ticket promedio','Ventas','sales',['a4'],['date','seller','client','total'],'chart'],
 ['gross-profit','Lucro bruto','Rentabilidad','sales',['a4','landscape'],['date','number','seller','subtotal','discount','total'],'chart'],
 ['payment-methods','Ventas por medio de pago','Ventas','sales',['a4','landscape'],['date','number','client','payment','total'],'cash'],
 ['seller-commission','Comisión por vendedor','Ventas','employees',['a4','landscape'],['name','role','sales','total','ticket','commission'],'badge'],
 ['sales-products','Ventas por producto','Ventas','products',['a4','landscape'],['code','name','category','stock','price','profit'],'box'],
 ['sales-category','Ventas por categoría y producto','Ventas','products',['a4','landscape'],['category','code','name','stock','price'],'box'],
 ['sales-client-category','Ventas por cliente y categoría','Ventas','clients',['a4','landscape'],['code','name','type','purchases','total','balance'],'users'],
 ['client-ranking','Ranking de clientes','Clientes','clients',['a4','landscape'],['name','type','purchases','total','balance'],'users'],
 ['client-products','Productos comprados por cliente','Clientes','clients',['a4','landscape'],['code','name','purchases','total','balance'],'users'],
 ['product-clients','Clientes compradores por producto','Clientes','products',['a4','landscape'],['code','name','category','stock','price'],'users'],
 ['peak-hours','Horario de pico','Ventas','sales',['a4'],['date','time','number','client','total'],'calendar'],
 ['product-profit','Rentabilidad por producto','Rentabilidad','products',['a4','landscape'],['code','name','cost','price','profit','stock'],'chart'],
 ['income-expense','Ingresos y gastos','Rentabilidad','cash',['a4','landscape'],['date','type','description','employee','income','expense','amount'],'wallet'],
 ['stock-movements','Movimentación de productos','Inventario','stock',['a4','landscape'],['date','product','code','type','quantity','reason','employee'],'transfer'],
 ['internal-use','Uso y consumo interno','Inventario','stock',['a4','landscape'],['date','product','code','quantity','reason','employee'],'box'],
 ['stock-position','Posición actual de stock','Inventario','products',['a4','landscape'],['code','name','category','stock','minimum','cost','price'],'box'],
 ['payables-due','Cuentas por vencer','Financiero','payables',['a4','landscape'],['due','description','supplier','status','amount'],'calendar'],
 ['payables-paid','Cuentas pagadas','Financiero','payables',['a4','landscape'],['due','description','supplier','status','amount'],'check'],
 ['purchases-product','Compras por producto','Compras','purchases',['a4','landscape'],['date','document','product','quantity','cost','total'],'box'],
 ['purchases-supplier','Compras por proveedor','Compras','purchases',['a4','landscape'],['date','document','supplier','quantity','total'],'store'],
 ['supplier-sales','Ventas por proveedor','Compras','products',['a4','landscape'],['supplier','code','name','stock','cost','price','profit'],'store'],
 ['fiscal-issued','Documentos fiscales emitidos','Fiscal','fiscal',['a4','landscape'],['date','number','model','client','status','total'],'receipt'],
 ['nfce-list','Relación de NFC-e','Fiscal','fiscal',['a4','landscape'],['date','number','client','status','total'],'receipt'],
 ['nfe-list','Relación de NF-e','Fiscal','fiscal',['a4','landscape'],['date','number','client','status','total'],'receipt'],
 ['cfop','Documentos por CFOP','Fiscal','fiscal',['a4','landscape'],['date','number','model','cfop','status','total'],'receipt'],
 ['sales-tax','Ventas por tributación','Fiscal','fiscal',['a4','landscape'],['date','number','model','cfop','client','total'],'chart']
].map(([id,title,category,source,allowedFormats,defaultFields,icon])=>({id,title,category,source,allowedFormats,defaultFields,icon}));
const modelById=id=>models.find(model=>model.id===id);
const ensureSettings=()=>state.settings.documentTemplates||(state.settings.documentTemplates={});
const configFor=model=>({title:model.title,format:model.allowedFormats[0],style:'modern',accent:state.settings.appearance?.accent||state.settings.accent||'#e20b13',fontSize:'medium',showLogo:true,showBusiness:true,showPeriod:true,showSignature:false,footer:'Documento generado por GRASSI PDV & ERP',fields:model.defaultFields,...ensureSettings()[model.id]});
const fieldLabel=(source,key)=>fieldSets[source]?.find(([id])=>id===key)?.[1]||key;
const safeDate=value=>{try{return date(value)}catch{return'—'}};
const safeTime=value=>{try{return time(value)}catch{return'—'}};
function sourceRows(source){
 if(source==='sales')return(state.sales||[]).map(s=>({number:s.id,date:safeDate(s.date),time:safeTime(s.date),client:s.client||'Consumidor final',seller:s.employee||'—',payment:s.payment||'—',kind:s.type||'Venta',items:s.items||0,subtotal:money(s.subtotal??s.total),discount:money(s.discountTotal||0),total:money(s.total)}));
 if(source==='products')return(state.products||[]).map(p=>({code:p.code||p.ean||'—',name:p.name,category:p.category||'—',unit:p.unit||'Unidad',stock:Number(p.stock||0).toLocaleString(locale()),minimum:Number(p.minStock||0).toLocaleString(locale()),cost:money(p.cost),price:money(p.price),wholesale:money(p.wholesale),supplier:p.supplier||'—',profit:`${p.cost?Math.round((p.price-p.cost)/p.cost*100):0}%`}));
 if(source==='clients')return(state.clients||[]).map(c=>({code:c.code||'—',name:c.name,type:c.type||'—',document:c.document||'—',phone:c.phone||'—',city:c.city||'—',balance:money(c.balance),purchases:c.purchases||0,total:money(c.total)}));
 if(source==='cash')return(state.cash||[]).map(m=>({date:safeDate(m.date),time:safeTime(m.date),type:m.type==='in'?'Entrada':'Salida',description:m.description,employee:m.employee||'—',income:m.type==='in'?money(m.amount):'—',expense:m.type==='out'?money(m.amount):'—',amount:money(m.amount),client:m.client||'—'}));
 if(source==='stock')return(state.stockMovements||[]).map(m=>{const p=state.products.find(x=>x.id===m.productId);return{date:safeDate(m.date),time:safeTime(m.date),product:p?.name||'Producto eliminado',code:p?.code||'—',type:m.type==='in'?'Entrada':m.type==='out'?'Salida':'Corrección',quantity:Number(m.amount||0).toLocaleString(locale()),reason:m.reason||'—',employee:m.employee||'—'}});
 if(source==='employees')return(state.employees||[]).map(e=>({name:e.name,role:e.role||'—',sales:e.sales||0,total:money(e.total),ticket:money(e.ticket),commission:money(Number(e.total||0)*.01),goal:`${e.goal||0}%`}));
 if(source==='closings')return(state.closings||[]).map(c=>({date:safeDate(c.date),opened:safeTime(c.openedAt),closed:safeTime(c.date),employee:c.employee||'—',income:money(c.entries),expense:money(c.exits),total:money(c.total),reason:c.reason||'—'}));
 return[];
}
function summaryFor(model,rows){const label={sales:'registros de venta',products:'productos',clients:'clientes',cash:'movimientos',stock:'movimientos',employees:'funcionarios',closings:'cierres',payables:'cuentas',purchases:'compras',fiscal:'documentos'}[model.source]||'registros';return`${rows.length} ${label}`}
function sheetHtml(model,config){const rows=sourceRows(model.source),selected=(config.fields||model.defaultFields).filter(key=>fieldSets[model.source]?.some(([id])=>id===key)),fields=selected.length?selected:model.defaultFields.slice(0,4),sample=rows.slice(0,config.format==='label'?1:10),logo=config.showLogo?(state.settings.logo?`<img src="${esc(state.settings.logo)}" alt="">`:`<i>${esc((state.settings.businessName||'G')[0])}</i>`):'';return`<article class="document-sheet format-${esc(config.format)} style-${esc(config.style)} font-${esc(config.fontSize)}" style="--doc-accent:${esc(config.accent)}"><header>${logo}<div>${config.showBusiness?`<strong>${esc(state.settings.businessName||'GRASSI')}</strong><span>${esc(state.settings.legalName||'')}</span><small>${esc([state.settings.nit&&`NIT ${state.settings.nit}`,state.settings.phone,state.settings.city].filter(Boolean).join(' · '))}</small>`:''}</div></header><section class="document-title"><div><small>GRASSI · DOCUMENTO</small><h2>${esc(config.title)}</h2></div>${config.showPeriod?`<span>Generado: ${safeDate(new Date())}<br>${safeTime(new Date())}</span>`:''}</section><div class="document-table-wrap"><table><thead><tr>${fields.map(key=>`<th>${esc(fieldLabel(model.source,key))}</th>`).join('')}</tr></thead><tbody>${sample.map(row=>`<tr>${fields.map(key=>`<td>${esc(row[key]??'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${fields.length}">Sin datos registrados para este modelo.</td></tr>`}</tbody></table></div><div class="document-summary"><span>${esc(summaryFor(model,rows))}</span><b>${rows.length?`Actualizado ${safeDate(new Date())}`:'Modelo listo para nuevos registros'}</b></div>${config.showSignature?'<div class="document-signatures"><span>Responsable</span><span>Cliente / receptor</span></div>':''}<footer>${esc(config.footer||'')}</footer></article>`}
function editorConfig(form){const data=new FormData(form),model=modelById(form.dataset.id);return{title:data.get('title')||model.title,format:data.get('format')||model.allowedFormats[0],style:data.get('style')||'modern',accent:data.get('accent')||'#e20b13',fontSize:data.get('fontSize')||'medium',showLogo:data.has('showLogo'),showBusiness:data.has('showBusiness'),showPeriod:data.has('showPeriod'),showSignature:data.has('showSignature'),footer:data.get('footer')||'',fields:data.getAll('fields')}}
function updatePreview(form){const model=modelById(form?.dataset.id),preview=form?.querySelector('[data-document-preview]');if(model&&preview)preview.innerHTML=sheetHtml(model,editorConfig(form))}
function openEditor(id){const model=modelById(id);if(!model)return;const config=configFor(model),fields=fieldSets[model.source]||[];openLayer(`${layerHead('Editor de documento')}<form id="documentTemplateForm" data-id="${model.id}"><div class="layer-body document-editor"><aside class="document-controls"><div class="field"><label>Nombre del modelo</label><input name="title" value="${esc(config.title)}"></div><div class="form-grid"><div class="field"><label>Formato</label><select name="format">${model.allowedFormats.map(id=>`<option value="${id}" ${config.format===id?'selected':''}>${formats[id]}</option>`).join('')}</select></div><div class="field"><label>Estilo</label><select name="style">${Object.entries(styles).map(([id,label])=>`<option value="${id}" ${config.style===id?'selected':''}>${label}</option>`).join('')}</select></div><div class="field"><label>Color principal</label><input name="accent" type="color" value="${esc(config.accent)}"></div><div class="field"><label>Tamaño del texto</label><select name="fontSize">${[['small','Pequeño'],['medium','Mediano'],['large','Grande']].map(([id,label])=>`<option value="${id}" ${config.fontSize===id?'selected':''}>${label}</option>`).join('')}</select></div></div><div class="document-switches">${[['showLogo','Mostrar logotipo'],['showBusiness','Datos de la empresa'],['showPeriod','Fecha y período'],['showSignature','Espacio para firmas']].map(([name,label])=>`<label><input type="checkbox" name="${name}" ${config[name]?'checked':''}><span>${label}</span></label>`).join('')}</div><div class="field"><label>Campos y columnas</label><div class="document-field-list">${fields.map(([key,label])=>`<label><input type="checkbox" name="fields" value="${key}" ${config.fields.includes(key)?'checked':''}><span>${esc(label)}</span></label>`).join('')}</div></div><div class="field"><label>Texto del pie</label><textarea name="footer" rows="3">${esc(config.footer)}</textarea></div><button type="button" class="btn secondary" data-doc-reset="${model.id}">Restaurar modelo original</button></aside><main class="document-preview" data-document-preview>${sheetHtml(model,config)}</main></div><footer class="layer-foot"><button type="button" class="btn" data-action="close-layer">Cancelar</button><button type="button" class="btn secondary" data-doc-print>${svg('receipt')} Imprimir / PDF</button><button class="btn primary" type="submit">Guardar modelo</button></footer></form>`,'modal document-template-modal')}
function render(){ensureSettings();const categories=['Todos',...new Set(models.map(model=>model.category))],visible=models.filter(model=>studio.category==='Todos'||model.category===studio.category);return`<section class="page page-documents">${pageHeader('Documentos y modelos',models.length)}<div class="page-body"><div class="document-hero"><div><p class="eyebrow">CENTRO DE DOCUMENTOS</p><h2>Modelos listos y completamente editables</h2><p>Personalice formatos A4, térmicos y etiquetas. Elija columnas, colores, estilo, logotipo, firmas y pie de página.</p></div><span>${svg('receipt')}<b>${models.length}</b><small>modelos</small></span></div><div class="document-category-strip">${categories.map(category=>`<button class="${studio.category===category?'active':''}" data-doc-category="${esc(category)}">${esc(category)} <b>${category==='Todos'?models.length:models.filter(model=>model.category===category).length}</b></button>`).join('')}</div><div class="document-model-grid">${visible.map(model=>{const config=configFor(model);return`<article class="document-model-card"><header><span>${svg(model.icon)}</span><small>${esc(model.category)}</small></header><h3>${esc(config.title)}</h3><p>${esc(formats[config.format])} · ${esc(styles[config.style])}</p><div>${model.allowedFormats.map(id=>`<i>${esc(formats[id].replace('A4 ','A4 ').replace('Térmico ','').replace(' mm','mm'))}</i>`).join('')}</div><footer><button class="btn secondary" data-doc-export="${model.id}" title="Exportar configuración">${svg('download')}</button><button class="btn primary" data-doc-template="${model.id}">Editar y generar</button></footer></article>`}).join('')}</div></div></section>`}
document.addEventListener('click',event=>{const category=event.target.closest('[data-doc-category]');if(category){studio.category=category.dataset.docCategory;return globalThis.render?.()}const open=event.target.closest('[data-doc-template]');if(open)return openEditor(open.dataset.docTemplate);const reset=event.target.closest('[data-doc-reset]');if(reset){delete ensureSettings()[reset.dataset.docReset];save();return openEditor(reset.dataset.docReset)}const print=event.target.closest('[data-doc-print]');if(print){document.body.classList.add('printing-document');window.print();return}const exportButton=event.target.closest('[data-doc-export]');if(exportButton){const model=modelById(exportButton.dataset.docExport),config=configFor(model);return download(`modelo-${model.id}.json`,JSON.stringify({model:model.id,config},null,2),'application/json')}});
document.addEventListener('input',event=>{const form=event.target.closest('#documentTemplateForm');if(form)updatePreview(form)});
document.addEventListener('change',event=>{const form=event.target.closest('#documentTemplateForm');if(form)updatePreview(form)});
document.addEventListener('submit',async event=>{const form=event.target.closest('#documentTemplateForm');if(!form)return;event.preventDefault();event.stopImmediatePropagation();const model=modelById(form.dataset.id);ensureSettings()[model.id]=editorConfig(form);save();await GrassiBackend.saveSettings(state.settings).catch(()=>{});auditEvent('Modelo de documento atualizado','Documentos',model.title,'success');closeLayer();globalThis.render?.();toast('Modelo guardado')},true);
window.addEventListener('afterprint',()=>document.body.classList.remove('printing-document'));
window.GrassiDocuments={render,openEditor,models};
})();
